### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by d4rkm0nkey** [AbsolemJackdaw/PaintingsFabric#8]
[13:08:28] [main/INFO]: Loading for game Minecraft 1.17.1
[13:08:28] [main/INFO]: Loading 49 mods:
	- fabric 0.40.8+1.17
	- fabric-api-base 0.3.0+a02b446318
	- fabric-api-lookup-api-v1 1.3.0+cbda931818
	- fabric-biome-api-v1 3.2.0+cbda931818
	- fabric-blockrenderlayer-v1 1.1.5+a02b446318
	- fabric-command-api-v1 1.1.3+5ab9934c18
	- fabric-commands-v0 0.2.2+92519afa18
	- fabric-containers-v0 0.1.12+cbda931818
	- fabric-content-registries-v0 0.3.0+cbda931818
	- fabric-crash-report-info-v1 0.1.5+be9da31018
	- fabric-dimensions-v1 2.0.11+6cefd57718
	- fabric-entity-events-v1 1.2.3+87cc6e4c18
	- fabric-events-interaction-v0 0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0 0.2.1+92519afa18
	- fabric-game-rule-api-v1 1.0.7+cbda931818
	- fabric-item-api-v1 1.2.4+cbda931818
	- fabric-item-groups-v0 0.2.10+b7ab612118
	- fabric-key-binding-api-v1 1.0.4+cbda931818
	- fabric-keybindings-v0 0.2.2+36b77c3e18
	- fabric-lifecycle-events-v1 1.4.4+a02b446318
	- fabric-loot-tables-v1 1.0.4+a02b446318
	- fabric-mining-levels-v0 0.1.3+92519afa18
	- fabric-models-v0 0.3.0+a02b446318
	- fabric-networking-api-v1 1.0.13+cbda931818
	- fabric-networking-blockentity-v0 0.2.11+a02b446318
	- fabric-networking-v0 0.3.2+92519afa18
	- fabric-object-builder-api-v1 1.10.9+cbda931818
	- fabric-object-builders-v0 0.7.3+a02b446318
	- fabric-particles-v1 0.2.4+a02b446318
	- fabric-registry-sync-v0 0.7.11+7931163218
	- fabric-renderer-api-v1 0.4.4+cbda931818
	- fabric-renderer-indigo 0.4.8+cbda931818
	- fabric-renderer-registries-v1 3.2.4+7931163218
	- fabric-rendering-data-attachment-v1 0.1.5+a02b446318
	- fabric-rendering-fluids-v1 0.1.14+4658223018
	- fabric-rendering-v0 1.1.5+7931163218
	- fabric-rendering-v1 1.9.0+7931163218
	- fabric-resource-loader-v0 0.4.8+a00e834b18
	- fabric-screen-api-v1 1.0.4+cbda931818
	- fabric-screen-handler-api-v1 1.1.8+cbda931818
	- fabric-structure-api-v1 1.1.13+5ab9934c18
	- fabric-tag-extensions-v0 1.2.1+b06cb95b18
	- fabric-textures-v0 1.0.6+a02b446318
	- fabric-tool-attribute-api-v1 1.2.12+b7ab612118
	- fabric-transfer-api-v1 1.4.0+7931163218
	- fabricloader 0.12.1
	- java 16
	- minecraft 1.17.1
	- paintings 1.17.1-1.0.0.3
[13:08:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/tim/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.10.2+mixin.0.8.4/sponge-mixin-0.10.2+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[13:08:29] [main/INFO]: Compatibility level set to JAVA_16
[13:08:34] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:08:36] [Render thread/INFO]: Setting user: lTeaJayl
[13:08:36] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zdc000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[13:08:36] [Render thread/INFO]: loading json file and contents for paintings.
[13:08:36] [Render thread/INFO]: Copying Over Base Template to /paintings
[13:08:36] [Render thread/INFO]: Reading out ResourcePacks to find painting related json files
[13:08:36] [Render thread/INFO]: Started Reading all json files in /painting directory
[13:08:36] [Render thread/INFO]: ./paintings/paintings.json
[13:08:36] [Render thread/INFO]: Loaded json painting abstract_blue , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting abstract_rainbow , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting abstract_red , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting abstract_sunset , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting arachnophobe , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting barn_owl , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting big_z , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting blue_bird , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting bluesclues , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting borgia , 16 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting cane , 16 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting cat_black , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting cat_gray , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting cat_orange , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting cat , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting colorful_squares , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting crest , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting danger_zone , 32 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting decorative_gun , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting exit_down , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting exit_up , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting exit_left , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting exit_right , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_bat , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_chicken , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_cow , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_creeper , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_dog , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_enderman , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_pig , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_pigman , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_silverfish , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_skeleton , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_squid , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting face_zombie , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting fishes , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting flowers , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting fruits , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting ghost , 16 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting glowlamp , 32 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting glowstone_hourglass , 16 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting iluvmc , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting link , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting mine_prosperity , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting no_trespassing_for_mobs , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting ocelot , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting penguin , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting pig_on_a_cliff , 32 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting pkmn_blue , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting pkmn_red , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting pkmn_green , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting plains_hut , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting portrait_2 , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting portrait , 32 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting prison , 16 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting prosperity , 16 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting rest , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting skeleton , 16 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting sky , 32 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting skyblock , 32 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting snake , 16 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting snow_landscape , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting subaraki , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting synth_city , 16 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting tapistry_a , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting tapistry_b , 16 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting tapistry_purple , 16 x 32
[13:08:36] [Render thread/INFO]: Loaded json painting torched , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting waterfall , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting whale , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting wheat_field , 32 x 16
[13:08:36] [Render thread/INFO]: Loaded json painting wolf_in_wheat , 32 x 16
[13:08:36] [Render thread/INFO]: Registered painting paintings:abstract_blue
[13:08:36] [Render thread/INFO]: Registered painting paintings:abstract_rainbow
[13:08:36] [Render thread/INFO]: Registered painting paintings:abstract_red
[13:08:36] [Render thread/INFO]: Registered painting paintings:abstract_sunset
[13:08:36] [Render thread/INFO]: Registered painting paintings:arachnophobe
[13:08:36] [Render thread/INFO]: Registered painting paintings:barn_owl
[13:08:36] [Render thread/INFO]: Registered painting paintings:big_z
[13:08:36] [Render thread/INFO]: Registered painting paintings:blue_bird
[13:08:36] [Render thread/INFO]: Registered painting paintings:bluesclues
[13:08:36] [Render thread/INFO]: Registered painting paintings:borgia
[13:08:36] [Render thread/INFO]: Registered painting paintings:cane
[13:08:36] [Render thread/INFO]: Registered painting paintings:cat_black
[13:08:36] [Render thread/INFO]: Registered painting paintings:cat_gray
[13:08:36] [Render thread/INFO]: Registered painting paintings:cat_orange
[13:08:36] [Render thread/INFO]: Registered painting paintings:cat
[13:08:36] [Render thread/INFO]: Registered painting paintings:colorful_squares
[13:08:36] [Render thread/INFO]: Registered painting paintings:crest
[13:08:36] [Render thread/INFO]: Registered painting paintings:danger_zone
[13:08:36] [Render thread/INFO]: Registered painting paintings:decorative_gun
[13:08:36] [Render thread/INFO]: Registered painting paintings:exit_down
[13:08:36] [Render thread/INFO]: Registered painting paintings:exit_up
[13:08:36] [Render thread/INFO]: Registered painting paintings:exit_left
[13:08:36] [Render thread/INFO]: Registered painting paintings:exit_right
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_bat
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_chicken
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_cow
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_creeper
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_dog
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_enderman
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_pig
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_pigman
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_silverfish
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_skeleton
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_squid
[13:08:36] [Render thread/INFO]: Registered painting paintings:face_zombie
[13:08:36] [Render thread/INFO]: Registered painting paintings:fishes
[13:08:36] [Render thread/INFO]: Registered painting paintings:flowers
[13:08:36] [Render thread/INFO]: Registered painting paintings:fruits
[13:08:36] [Render thread/INFO]: Registered painting paintings:ghost
[13:08:36] [Render thread/INFO]: Registered painting paintings:glowlamp
[13:08:36] [Render thread/INFO]: Registered painting paintings:glowstone_hourglass
[13:08:36] [Render thread/INFO]: Registered painting paintings:iluvmc
[13:08:36] [Render thread/INFO]: Registered painting paintings:link
[13:08:36] [Render thread/INFO]: Registered painting paintings:mine_prosperity
[13:08:36] [Render thread/INFO]: Registered painting paintings:no_trespassing_for_mobs
[13:08:36] [Render thread/INFO]: Registered painting paintings:ocelot
[13:08:36] [Render thread/INFO]: Registered painting paintings:penguin
[13:08:36] [Render thread/INFO]: Registered painting paintings:pig_on_a_cliff
[13:08:36] [Render thread/INFO]: Registered painting paintings:pkmn_blue
[13:08:36] [Render thread/INFO]: Registered painting paintings:pkmn_red
[13:08:36] [Render thread/INFO]: Registered painting paintings:pkmn_green
[13:08:36] [Render thread/INFO]: Registered painting paintings:plains_hut
[13:08:36] [Render thread/INFO]: Registered painting paintings:portrait_2
[13:08:36] [Render thread/INFO]: Registered painting paintings:portrait
[13:08:36] [Render thread/INFO]: Registered painting paintings:prison
[13:08:36] [Render thread/INFO]: Registered painting paintings:prosperity
[13:08:36] [Render thread/INFO]: Registered painting paintings:rest
[13:08:36] [Render thread/INFO]: Registered painting paintings:skeleton
[13:08:36] [Render thread/INFO]: Registered painting paintings:sky
[13:08:36] [Render thread/INFO]: Registered painting paintings:skyblock
[13:08:36] [Render thread/INFO]: Registered painting paintings:snake
[13:08:36] [Render thread/INFO]: Registered painting paintings:snow_landscape
[13:08:36] [Render thread/INFO]: Registered painting paintings:subaraki
[13:08:36] [Render thread/INFO]: Registered painting paintings:synth_city
[13:08:36] [Render thread/INFO]: Registered painting paintings:tapistry_a
[13:08:36] [Render thread/INFO]: Registered painting paintings:tapistry_b
[13:08:36] [Render thread/INFO]: Registered painting paintings:tapistry_purple
[13:08:36] [Render thread/INFO]: Registered painting paintings:torched
[13:08:36] [Render thread/INFO]: Registered painting paintings:waterfall
[13:08:36] [Render thread/INFO]: Registered painting paintings:whale
[13:08:36] [Render thread/INFO]: Registered painting paintings:wheat_field
[13:08:36] [Render thread/INFO]: Registered painting paintings:wolf_in_wheat
---- Minecraft Crash Report ----
// You're mean.

Time: 10/15/21, 1:08 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'paintings'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:149)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at subaraki.paintings.mod.Paintings.onInitialize(Paintings.java:29)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 19 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 28 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.4.0-88-generic
	Java Version: 16.0.1, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 1254824272 bytes (1196 MiB) / 1585446912 bytes (1512 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: GM204 [GeForce GTX 970]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x13c2
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 10026.38
	Virtual memory used (MB): 6714.03
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms1024m -Xmx4096m
	Fabric Mods: 
		fabric: Fabric API 0.40.8+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+cbda931818
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
		fabricloader: Fabric Loader 0.12.1
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17.1
		paintings: Paintings ++ 1.17.1-1.0.0.3
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/tim/.local/share/multimc/instances/mods you should know 1.17/.minecraft/crash-reports/crash-2021-10-15_13.08.36-client.txt
Process exited with code 255.
Clipboard copy at: 15 Oct 2021 13:09:02 +0200

**Comment by strikerrocker** [comment]
Install the cloth config fabric mod from curseforge.
